ShoeShopOnline/ShoeShopOnline.WebApp/Controllers/HomesController.cs
using ShoeShopOnline.Common;
using ShoeShopOnline.Model.DAL;
using ShoeShopOnline.Model.Dao;
using ShoeShopOnline.WebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ShoeShopOnline.WebApp.Controllers
{
    public class HomesController : BaseController
    {
        private ShoeShopOnlineDbContext db = new ShoeShopOnlineDbContext();
        private const string CartSession = "CartSession";

        // GET: Homes
        public ActionResult Index()
        {
            return View();
        }
        // Footer
        [ChildActionOnly]
        public ActionResult Footer()
        {
            var result = db.Footer.SingleOrDefault(x => x.IsDeleted == false);
            return PartialView(result);
        }
        //Main menu
        [ChildActionOnly]
        public ActionResult MainMenu()
        {
            List<Menu> dsmenu = new List<Menu>();
            dsmenu = db.Menu.Where(x => x.ParentId == null && x.IsDeleted == false).OrderBy(x => x.DisplayOrder).ToList();
            return PartialView(dsmenu);
        }
        [ChildActionOnly]
        public ActionResult SubMenu(int ParentId)
        {
            List<Menu> lst = new List<Menu>();
            lst = db.Menu.Where(x => x.ParentId == ParentId && x.IsDeleted == false).OrderBy(x => x.DisplayOrder).ToList();
            ViewBag.Count = lst.Count();
            return PartialView(lst);
        }
        //Slide
        [ChildActionOnly]
        public PartialViewResult Slide()
        {
            List<Slide> getSlide = new List<Slide>();
            getSlide = db.Slide.Where(x => x.IsDeleted == false).ToList();
            ViewBag.Count = getSlide.Count();
            return PartialView(getSlide);
        }
        //Footer -- Contact
        [ChildActionOnly]
        public ActionResult Contact()
        {
            List<Contact> list = new List<Contact>();
            list = db.Contact.Where(x => x.IsDeleted == false).ToList();
            ViewBag.Count = list.Count();
            return PartialView(list);
        }
        [ChildActionOnly]
        public PartialViewResult HeaderCart()
        {
            var cart = Session[CommonConstants.CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            return PartialView(list);
        }
        //Cancel payment - order for customer
        public ActionResult CancelOrder(Guid? id)
        {
            Order order = db.Order.Find(id);
            if (order.Status == true)
            {
                SetAlert("Đơn hàng đã được vận chuyển, bạn không thể hủy!","warning");
            }
            else
            {
                order.IsDeleted = true;
                OrderDetail orderDetail = db.OrderDetail.FirstOrDefault(x => x.OrderId == order.Id);
                Product product = db.Product.FirstOrDefault(x => x.Id == orderDetail.ProductId);
                if (orderDetail != null)
                {
                    orderDetail.IsDeleted = true;
                }
                if (product != null)
                {
                    product.Quantity += orderDetail.Quantity;
                }
                db.SaveChanges();
                SetAlert("Bạn vừa hủy một đơn hàng", "warning");
            }
            return Redirect("/lich-su-mua-hang");
        }
        //Payment history
        public ActionResult HistoryPayment()
        {
            var session = (UserLogin)Session[CommonConstants.USER_SESSION];
            if (session != null)
            {
                return View(db.Order.Where(x => x.UserId == session.UserId && x.IsDeleted == false).ToList());
            }
            else
            {
                SetAlert("Bạn cần đăng nhập để thực hiện", "warning");
                return Redirect("/dang-nhap");
            }
        }
        public ActionResult HistoryPaymentDetail(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderDetail orderDetail = new OrderDetail();
            Order order = db.Order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(db.OrderDetail.Where(x => x.OrderId == order.Id).OrderByDescending(x => x.CreatedOn).ToList());
        }
        //Cancel order
        public ActionResult CancelOrderView()
        {
            var session = (UserLogin)Session[CommonConstants.USER_SESSION];
            if (session != null)
            {
                return View(db.Order.Where(x => x.UserId == session.UserId && x.IsDeleted == true).ToList());
            }
            else
            {
                SetAlert("Bạn cần đăng nhập để thực hiện", "warning");
                return Redirect("/dang-nhap");
            }
        }
        //Undo order
        public ActionResult UndoOrder(Guid? id)
        {
            Order order = db.Order.Find(id);
            order.IsDeleted = false;
            //Undo in order detail and Add turn quantity of product
            OrderDetail orderDetail = db.OrderDetail.FirstOrDefault(x => x.OrderId == order.Id);
            Product product = db.Product.FirstOrDefault(x => x.Id == orderDetail.ProductId);
            if (orderDetail != null)
            {
                orderDetail.IsDeleted = false;
            }
            if (product != null)
            {
                product.Quantity -= orderDetail.Quantity;
            }
            db.SaveChanges();
            SetAlert("Phục hồi đơn hàng thành công", "success");
            return Redirect("/lich-su-mua-hang");
        }
    }
}

ShoeShopOnline/ShoeShopOnline.WebApp/Controllers/ProductController.cs
using PagedList;
using ShoeShopOnline.Model.DAL;
using ShoeShopOnline.Model.Dao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ShoeShopOnline.WebApp.Controllers
{
    public class ProductController : Controller
    {
        private ShoeShopOnlineDbContext db = new ShoeShopOnlineDbContext();
        // GET: Products
        public ActionResult LoadHotProduct()
        {
            List<Product> list = new List<Product>();
            list = db.Product.Where(x => x.IsDeleted == false && x.TopHot == true).OrderByDescending(x => x.CreatedOn).Take(2).ToList();
            ViewBag.Count = list.Count();
            return PartialView(list);
        }
        public ActionResult LoadNormalProduct1()
        {
            List<Product> list = new List<Product>();
            list = db.Product.Where(x => x.IsDeleted == false && x.IsNormalProduct1 == true).OrderByDescending(x => x.CreatedOn).Take(4).ToList();
            ViewBag.Count = list.Count();
            return PartialView(list);
        }
        public ActionResult LoadNormalProduct2()
        {
            List<Product> list = new List<Product>();
            list = db.Product.Where(x => x.IsDeleted == false && x.IsNormalProduct2 == true).OrderByDescending(x => x.CreatedOn).Take(4).ToList();
            ViewBag.Count = list.Count();
            return PartialView(list);
        }
        public ActionResult LoadNewProduct()
        {
            List<Product> list = new List<Product>();
            list = db.Product.Where(x => x.IsDeleted == false && x.IsNewProduct == true).OrderByDescending(x => x.CreatedOn).Take(3).ToList();
            ViewBag.Count = list.Count();
            return PartialView(list);
        }

        public ActionResult LoadLastedProduct(Guid? id)
        {
            Product product = db.Product.Find(id);
            List<Product> list = new List<Product>();
            list = db.Product.Where(x => x.IsDeleted == false && x.ProductCategoryId == product.ProductCategoryId && x.Id != product.Id).OrderByDescending(x => x.CreatedOn).Take(3).ToList();
            ViewBag.Count = list.Count();
            return PartialView(list);
        }

        //Detail of Product
        public ActionResult Details(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }
        //Load category for menu
        public ActionResult LoadCategory()
        {
            List<ProductCategory> productCategories = new List<ProductCategory>();
            productCategories = db.ProductCategory.Where(x => x.IsDeleted == false).ToList();
            var product = db.Product.ToList();
            ViewBag.Count = productCategories.Count();
            ViewBag.CountAllProduct = product.Count();
            return PartialView(productCategories);
        }
        //Load product from price
        public ActionResult CategoryDetail(ProductCategory productCategory)
        {
            List<Product> list = new List<Product>();
            list = db.Product.Where(x => x.IsDeleted == false && x.ProductCategoryId == productCategory.Id).ToList();
            ViewBag.Count = list.Count();
            return View(list);
        }
        //Load all product in 1 page
        public ActionResult LoadAllProduct(int? page)
        {
            List<Product> list = new List<Product>();
            list = db.Product.Where(x => x.IsDeleted == false).OrderByDescending(x => x.CreatedOn).ToList();
            ViewBag.Count = list.Count();
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            return View(list.ToPagedList(pageNumber, pageSize));
        }

        //Search auto complete
        public JsonResult ListName(string q)
        {
            var data = new ProductDao().ListName(q);
            return Json(new
            {
                data = data,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Search(string keyword)
        {
            var model = new ProductDao().Search(keyword);
            ViewBag.Keyword = keyword;
            ViewBag.Count = model.Count();
            return View(model);
        }
    }
}

ShoeShopOnline/ShoeShopOnline.WebApp/Views/Homes/CancelOrderView.cshtml
@model IEnumerable<ShoeShopOnline.Model.DAL.Order>

@{
    ViewBag.Title = "Lịch sử mua hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int i = 1;
}
<!--start-breadcrumbs-->
<div class="breadcrumbs">
    <div class="container">
        <div class="breadcrumbs-main">
            <ol class="breadcrumb">
                <li><a href="/trang-chu">Trang chủ</a></li>
                <li class="active">@ViewBag.Title</li>
            </ol>
        </div>
    </div>
</div>
<!--end-breadcrumbs-->


<div class="table-responsive container" style="margin-top: 10px;">
    <p>
        <a href="/lich-su-mua-hang" class="btn btn-group-sm btn-primary text-decoration-none">Lịch sử mua hàng</a>
    </p>
    <table class="table table-bordered table-striped table-condensed">
        <thead>
            <tr>
                <th>
                    STT
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ShipName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ShipPhone)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ShipAddress)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ShipEmail)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedOn)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-center">
                        @i
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ShipName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ShipPhone)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ShipAddress)
                    </td>
                    <td>gma
                        @Html.DisplayFor(modelItem => item.ShipEmail)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedOn)
                    </td>
                    <td>
                        @(item.Status ? "Đã xác nhận" : "Chưa xác nhận")
                    </td>
                    <td class="text-center">
                        <a class="btn-sm btn-group-sm btn-primary" href="/chi-tiet-don-hang/@item.Id"><i class="fas fa-info"></i></a>
                        <a class="btn-sm btn-group-sm btn-danger" onclick="return confirm('Xác nhận khôi phục đơn hàng!');" href="@Url.Action("UndoOrder", new { id = @item.Id})"><i class="fas fa-undo"></i></a>
                    </td>
                </tr>
                i++;
            }
        </tbody>
    </table>
    @if (Model.Count() <= 0)
    {
        <div class="text-center text-danger">Không có giao dịch</div>
    }
</div>

ShoeShopOnline/ShoeShopOnline.WebApp/Views/Homes/HistoryPayment.cshtml
@model IEnumerable<ShoeShopOnline.Model.DAL.Order>

@{
    ViewBag.Title = "Lịch sử mua hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int i = 1;
}
<!--start-breadcrumbs-->
<div class="breadcrumbs">
    <div class="container">
        <div class="breadcrumbs-main">
            <ol class="breadcrumb">
                <li><a href="/trang-chu">Trang chủ</a></li>
                <li class="active">@ViewBag.Title</li>
            </ol>
        </div>
    </div>
</div>
<!--end-breadcrumbs-->


<div class="table-responsive container" style="margin-top: 10px;">
    <p>
        <a href="/don-hang-da-huy" class="btn btn-group-sm btn-primary text-decoration-none">Đơn đã hủy</a>
    </p>
    <table class="table table-bordered table-striped table-condensed">
        <thead>
            <tr>
                <th>
                    STT
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ShipName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ShipPhone)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ShipAddress)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ShipEmail)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedOn)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-center">
                        @i
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ShipName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ShipPhone)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ShipAddress)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ShipEmail)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedOn)
                    </td>
                    <td>
                        @(item.Status ? "Đã xác nhận" : "Chưa xác nhận")
                    </td>
                    <td class="text-center">
                        <a class="btn-sm btn-group-sm btn-primary" href="/chi-tiet-don-hang/@item.Id"><i class="fas fa-info"></i></a>
                        <a class="btn-sm btn-group-sm btn-danger" onclick="return confirm('Xác nhận hủy đơn hàng!');" href="@Url.Action("CancelOrder", new { id = @item.Id})"><i class="far fa-trash-alt"></i></a>
                    </td>
                </tr>
                i++;
            }
        </tbody>
    </table>
    @if (Model.Count() <= 0)
    {
        <div class="text-center text-danger">Không có giao dịch</div>
    }
</div>

ShoeShopOnline/ShoeShopOnline.WebApp/Views/Homes/HistoryPaymentDetail.cshtml
@model IEnumerable<ShoeShopOnline.Model.DAL.OrderDetail>

@{
    ViewBag.Title = "Chi tiết đơn hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int i = 1;
}
<!--start-breadcrumbs-->
<div class="breadcrumbs">
    <div class="container">
        <div class="breadcrumbs-main">
            <ol class="breadcrumb">
                <li><a href="/trang-chu">Trang chủ</a></li>
                <li><a href="/lich-su-mua-hang">Lịch sử mua hàng</a></li>
                <li class="active">@ViewBag.Title</li>
            </ol>
        </div>
    </div>
</div>
<div class="container table-responsive" style="margin-top: 10px;">
    <table class="table table-bordered table-condensed table-hover table-striped">
        <tr class="thead-dark">
            <th>
                STT
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Order.ShipName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Total)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @i
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Order.ShipName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedOn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Total)
                </td>
            </tr>
            i++;
        }
    </table>
</div>

ShoeShopOnline/ShoeShopOnline.WebApp/Views/Homes/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!--banner-starts-->
@{ Html.RenderAction("Slide", "Homes");}
<!--banner-ends-->
<!--Slider-Starts-Here-->
<script src="~/Content/Client/js/responsiveslides.min.js"></script>
<script>
    // You can also use "$(window).load(function() {"
    $(function () {
        // Slideshow 4
        $("#slider4").responsiveSlides({
            auto: true,
            pager: true,
            nav: false,
            speed: 500,
            namespace: "callbacks",
            before: function () {
                $('.events').append("<li>before event fired.</li>");
            },
            after: function () {
                $('.events').append("<li>after event fired.</li>");
            }
        });

    });
</script>
<!--End-slider-script-->
<!--start-banner-bottom-->
@{Html.RenderAction("LoadHotProduct", "Product");}
<!--end-banner-bottom-->
<!--start-shoes-->
<div class="shoes">
    <div class="container">
        <div class="product-one">
            @{ Html.RenderAction("LoadNormalProduct1", "Product");}
            <div class="clearfix"> </div>
        </div>
        <div class="product-one">
            @{ Html.RenderAction("LoadNormalProduct2", "Product");}
            <div class="clearfix"> </div>
        </div>
    </div>
</div>
<!--end-shoes-->
<!--start-abt-shoe-->
<div class="abt-shoe">
    <div class="container">
        <div class="abt-shoe-main">
            @{Html.RenderAction("LoadNewProduct", "Product");}
            <div class="clearfix"> </div>
        </div>
    </div>
</div>
<!--end-abt-shoe-->